#!/bin/bash
######################################################################
# test_tymm                                             September 2000
# Horms                                           <horms@vergenet.net>
#
# Parallel test of tymm loging into a perdition server running
# on port 11000 on the local host
#
# perdition
# Mail retrieval proxy server
# Copyright (C) 1999-2002  Horms
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307  USA
#
######################################################################

TYMM=0
while [ $TYMM -lt 160 ]; do
  TYMM=$(( $TYMM + 1 ))
  { 
    echo "user tymm$TYMM" ; 
    sleep 1 ; 
    echo "pass flym" ; 
    sleep 1 ; 
    echo "stat" ; 
    sleep 1 ; 
    echo quit 
  } | nc localhost 11000 &
done

wait

