.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" perdition.8                                            December 2000
.\" Horms                                             horms@verge.net.au
.\"
.\" perdition
.\" Mail retrieval proxy server
.\" Copyright (C) 1999-2005  Horms <horms@verge.net.au>
.\" 
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of the
.\" License, or (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software Foundation,
.\" Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH PERDITION 8 "12th June 2003"
.SH NAME
perdition \- POP3 and IMAP4 proxy server
.SH SYNOPSIS
\fBperdition\fP [options]
.br
\fBperdition.pop3\fP [options]
.br
\fBperdition.pop3s\fP [options]
.br
\fBperdition.imap4\fP [options]
.br
\fBperdition.imap4s\fP [options]
.br
\fBperdition.imaps\fP [options]
.SH DESCRIPTION
\fBperdition\fP allows users to connect to a content\-free POP3 or IMAP4
server that will redirect them to their real POP3 or IMAP4 server
respectively. This enables mail retrieval for a domain to be split across
multiple real mail servers on a per user basis.  This can also be used to
as a POP3 or IMAP4 proxy especially in firewall applications.
.P
When a connection is made to perdition in POP3 mode, it reads the USER and
PASS commands and then refers to its popmap to find the real-server that
the user's connection should be forwarded to.  A connection is made to the
real-server and perdition then enters the USER and PASS commands. If
authentication is successful then perdition pipes data between the end-user
and the real-server.  If authentication fails then the real-server
connection is closed and the client connection is reset to the state it was
in on initial connection. That is new USER and PASS commands are expected.
Similarly in IMAP4 mode, perdition accepts the LOGIN command and passes the
username and password onto the real-server or authentication.
.P
No IMAP authentication schemes, other than the LOGIN command are
accepted.
.P
When invoked as \fBperdition.pop3\fP, \fBperdition.pop3s\fP,
\fBperdition.imap4\fP or \fBperdition.imap4s\fP then perdition will run in
POP3, POP3S, IMAP4 or IMAP4S mode respectively, unless overridden on the
command line or in the configuration file.  \fBperdition.imaps\fP also runs
perdition in IMAP4S mode and is provided to get around the truncation of
process names in the /proc filesystem on Linux which can cause init scripts
to fail to stop perdition correctly.
.SH OPTIONS
.TP
.B \-A|\-\-add_domain STATE[,STATE...][,STRIP_DEPTH]:
Appends a domain to the USER based on the IP address connected to
in given state(s). The domain name to append will be the reverse-lookup
of the IP address connected to. If there is no reverse lookup for
this IP address, then a domain will not be appended. Probably the easiest
way to enforce this mapping is to add entries to /etc/hosts.
.sp
The valid states are servername_lookup, local_authentication, 
remote_login and all
.sp
.B servername_lookup:
Append the domain to the username for lookup of username in
Popmap. Will not take effect if client_server_specification is in effect.
.sp
.B local_authentication:
Append the domain to the username for use in local
authentication. Only has effect if authenticate_in is in effect.
.sp
.B remote_login:
Send the username with the domain appended to the real-server for 
authentication.
.sp
.B all:
Short-Hand for all of above states.
.sp
The domain may also have leading levels striped, essentially
to convert a hostname to a domain name. The depth of the strip
defaults to 1, which would mean that www.au.vergenet.net would
become au.vergenet.net. A depth of 2 would cause it to become 
vergenet.net and so forth. A depth of 0 leaves the name unchanged.
The depth and may be specified by appending ",STRIP_DEPTH" to the state. 
For compatibility reasons the default depth is 1.
.sp
e.g. all,2
.sp
(the default value for add_domain is "")
.TP
.B \-a, \-\-authenticate_in:
User is authenticated by perdition before connection to back-end
server is made. Only available if perdition is compiled with pam
support.
.TP
.B \-B, \-\-no_bind_banner:
If bind_address is specified, then the address will be resolved
and the reverse\-lookup of this will be used in the greeting. This
option disables this behaviour an reverts to using the uname to
derive the hostname for the greeting.
.TP
.B \-b, \-\-bind_address SERVER[,SERVER...]:
Bind to these addresses and ports. interfaces with this address. 
Format is as per the \-\-outgoing_server option. If the port is
ommitted, then the listen_port will be used.
.sp
In non\-inetd mode, connections will only be accepted to the listed
servers. If un-set connections will be accepted on all addresses on the
listen_port.
.sp
(default "")
.TP
.B \-C|\-\-connection_logging:
Log interaction between clients, perdition and servers during
authentication phase.
.sp
\fBNote:\fP \-d|\-\-debug must be specified for this option to take effect.
.TP
.B \-\-connect_relog SECONDS:
How often to relog the connection.
For use in conjunction with POP and IMAP before SMTP.
If zero then the connection will not be reloged.
.br
(default 300)
.TP
.B \-c, \-\-client_server_specification:
Allow USER of the form user<delimiter>server[:port] to specify the
server and port for a user.
.TP
.B \-D, \-\-domain_delimiter STRING:
Delimiter between username and domain.
.br
(default "@")
.TP
.B \-d, \-\-debug:
Turn on verbose debugging.
.TP
.B \-e, \-\-explicit_domain STRING:
With \-A, use STRING as the default domain rather than deriving
from the IP address connected to.
.br
(default NULL)
.TP
.B \-F, \-\-log_facility FACILITY:
Facility to log to. If the facility has a leading '/' then it will
be treated as a file. If is "-" or "+" then log to stdout or stderr 
respectively. Otherwise it is assumed to be the name
of a syslog facility. See syslog.conf(5) for valid syslog facility
names.
.br
(default "mail")
.br 
Notes: If an error occurs before options are read it may be logged to 
stderr. If stdout or stderr is specified as the facility, then the 
process will not fork and detach from the terminal.
.TP
.B \-f, \-\-config_file FILENAME:
Name of config file to read.
Command line options override options set in config file.
.sp
The default is derived as follows:
.sp
The sysconfig dir ("/etc/perdition" for example)
is checked for <basename>.conf. If this is found then it is used.
So if perdition is invoked as /usr/sbin/perdition.pop3,
and /etc/perdition/perdition.pop3.conf exists then
it will be used.
.sp
Next the sysconfig dir is checked for peridtion.<protocol>.conf,
where protocol is the ASCII representation of the protocol
being used, one of "imap4", "imap4s", "pop3", or "pop3s".
So if perdition is being run in imap4 mode, and
/etc/perdition/perdition.imap4.conf exists, then
it is used. Note that the protocol name is lowercase.
.sp
Next the sysconfig dir is checked for perdition.conf,
if it is found then it is used.
.sp
If none of these files are found then no configuration file is used.
.TP
.B \-g, \-\-group GROUP:
Group to run as.
.br
(default "nobody")
.TP
.B \-h, \-\-help:
Display this message
.TP
.B \-I, \-\-capability, \-\-pop_capability, \-\-imap_capability STRING:
Capabilities for the protocol.
.sp
When using a POP3 based protocol, the capabilities should be
delimited by two spaces. This is because the capabilities themselves
may contain single spaces. The default is "UIDL  USER".
.sp
When using an IMAP4 based protocol, this string is taken as a string
literal that will be returned when a client issues the CAPABILITY
command. As such the capabilities should be space delimited.
The default is "IMAP4 IMAP4REV1". However, perdition does
support RFC 2088 non-synchronising string literals, if the real
servers also support this then the capability may be set to
"IMAP4 IMAP4REV1 LITERAL+".
.sp
If perdition is listening for TLS connections then the
capability STLS for POP3 or STARTTLS for IMAP4 will be
appended to the list of capabilities if it is not already 
present. Similarly these capabilities will be removed from
the list of capabilities if they are present and perdition is not
listening for TLS connections.
.sp
Perdition may also manipulate the capability in IMAP mode
to add and remove the LOGINDISABLED capability if the no_login capability
is in effect or if the ssl_mode includes tls_listen_force or
tls_outgoing_force.
.TP
.B \-i, \-\-inetd_mode:
Run in inetd mode
.TP
.B \-L, \-\-connection_limit LIMIT:
Maximum number of connections to accept simultaneously. A value of
zero sets no limit on the number of simultaneous connections.
.br
(default 0)
.TP
.B \-l, \-\-listen_port PORT_NUMBER|PORT_NAME:
Port to listen on.
.sp
The default is 110, 995, 143 and 993 in POP3, POP3S, IMAP4 and
IMAP4S mode respectively.
.TP
.B \-\-login_disabled:
Do not allow users to log in.
Also adds LOGINDISABLED to capability list in IMAP4 and IMAP4S mode.
.TP
.B \-\-log_passwd STATE:
Log the users password, otherwise just report it as "XXXXXX".
.br
(default "never")
.sp
.B fail: 
log the password on failed connection attepmts.
.sp
.B ok:
log the password on successful connection attepmts.
.sp
.B
never:
never log the password
.sp
.B
always:
always log the password
.TP
.B \-\-lower_case state[,state...]:
Convert usernames to lower case according the the locale in given
state(s). See A|add_domain for a description of the states.
.br
(default "(null)")
.TP
.B \-M, \-\-map_library FILENAME:
Library to open that provides functions to look up the server for a
user. An empty ("") library means that no library will be accessed 
and hence, no lookup will take place.
.br
(default "/usr/lib/libperditiondb_gdbm.so.0")
.TP
.B \-m, \-\-map_library_opt STRING:
String option to pass to database access function provided by the
library specified by the map_library directive. The treatment of
this string is up to the library. See perditiondb(5) for more details
of how individual map_libraries handle this string.
.br
(default "")
.TP
.B \-\-no_daemon:
Do not detach from terminal. Makes no sense if inetd_mode is in effect.
.TP
.B \-n, \-\-no_lookup:
Disable host and port lookup, implies no_bind_banner.
Please note that if this option is enabled, then perdition will
not resolve host or port names returned by popmap lookups, thus, your popmap
must return ip addresses and port numbers.
.TP
.B \-O, \-\-ok_line:
Use STRING as the OK line to send to the client. Overridden by server_resp_line.
OK and will be prepended to STRING, and in IMAP mode a tag
will also be prepended to the string.
.br
(default "You are so in")
.TP
.B \-\-server_ok_line:
This option is deprecated and may be removed in a future release.
Use server_resp_line instead.
If authentication with the real\-server is successful then send
the servers +OK line to the client, instead of generating one.
.TP
.TP
.B \-o, \-\-server_resp_line:
If authentication with the real\-server is successful then send
the servers response line to the client, instead of generating one.
.TP
.B \-P, \-\-protocol PROTOCOL:
Protocol to use.
.br
(default "POP3")
available protocols: "POP3, POP3S, IMAP4, IMAP4S"
.TP
.B \-p, \-\-outgoing_port PORT:
Default real-server port.
.br
See listen_port for defaults.
.TP
.B \-s, \-\-outgoing_server SERVER[,SERVER...]:
Define a server to use if a user is not in the popmap. Format is
servername|ip_address[:portname|portnumber]. Multiple servers may be 
delimited by a ','. If multiple servers are specified then they are 
used in a round robin fashion.
.br
(default "")
.TP
.B \-\-pid_file FILENAME:
Path for pidfile. Must be a full path starting with a '/'.
To allow perdition to remove the pid file after the owner of
the perdition process is changed to a non-root user, it is advised to
specify a pid file in a subdirectory of the system var state directory
(usually /var/run). This subdirectory should be unique to this perdition
invocation and will be created and have its owner and permissions set to
allow perdition to subsequently removed the pid file.  
.br
Empty for no pid file. Not used in inetd mode.
.br
(default <var_state_dir>/<basename>/<basename>.pid)
.TP
.B \-S, \-\-strip_domain STATE[,STATE]:
Allow USER of the from user<delimiter>domain where <delimiter>domain
will be striped off in given state(s).See add_domain for a
description of the states.
.TP
.B \-t, \-\-timeout SECONDS:
Idle timeout. Zero for infinite timeout.
.br
(default 1800)
.TP
.B \-u, \-\-username USERNAME:
User to run as.
.br
(default "nobody")
.TP
.B \-U, \-\-username_from_database:
If the servername in the popmap specified in the form:
user<delimiter>domain then use the username given by the servername.  If a
servername is given in this form then the domain will be used as the server
to connect to, regardless of this option.
.TP
.B \-q, \-\-quiet:
Only log errors. Overridden by debug
.TP
.B \-\-query_key FORMAT[,FORMAT...]:
Instead of using the username as supplied by the end user, possibly
modified by strip_domain, use the formats specified. The formats
will be used in order to query the popmap. The result from the first 
successful lookup will be used. The format is comprised of a string
of characters, delimited by ','. The following escape codes
are valid:
.sp
\\U: Long Username, the entire string supplied by 
    the end user, less any effects of 
    \-\-strip_domain.
.br
\\u: Short Username, the portion Long Username 
    before the domain delimiter.
.br
\\D: Domain Delimiter, as specified by 
    \-\-domain_delimiter
.br
\\d: Domain the portion Long Username after the
    domain delimiter.
.br
\\i: Source IP address of the connection
.br
\\I: Destination IP address of the connection
.br
\\p: Source port of the connection
.br
\\P: Destination port of the connection
.br
\\\\: Literal \\
.sp
As a ',' is the delimiter between formats, it cannot appear
within a format. All other characters other than the escape codes
above, and ',' are treated as literals.
.sp
Examples
.sp
Use the supplied username, the default behaviour
.br
\\U
.sp
Use the user portion of the supplied username, if this
doesn't work try the domain portion of the supplied 
username preceded by the domain delimiter
.br
\\u,\\D\\d
.sp
Use the destination IP address
.br
\\I
.sp
Escape codes interspersed with literals
.br
\\u\\da_domain,\\da_domain
.P
The options below relate to SSL/TLS support.
They are not available if perdition is compiled without SSL support.
.TP
.B \-\-ssl_mode MODE:
Use SSL and or TLS for the listening and/or outgoing connections.
A comma delimited list of: none, ssl_listen, ssl_outgoing,
ssl_all, tls_listen, tls_outgoing, tls_all, tls_listen_force,
tls_outgoing_force, tls_all_force. TLS is defined
in RFC 2595.
.br
(default "(null)")
.sp
.B none:
Do not use SSL or TLS for any connections. This is the same as
providing no option, the default.
.sp
.B ssl_listen:
When listening for incoming connections they will be treated
as SSL connections.
.sp
.B ssl_outgoing:
Use SSL to connect to real pop/imap servers.
.sp
.B ssl_all:
Short-Hand for ssl_listen,ssl_outgoing.
.sp
.B tls_listen:
When listening for incoming connections they will be treated
as TLS connections.
.sp
.B tls_outgoing:
Use TLS to connect to real pop/imap servers.
.sp
.B tls_all:
Short-Hand for tls_listen,tls_outgoing.
.sp
.B tls_listen_force:
Do not accept plain text authentication. In IMAP4 and IMAP4S mode,
the LOGINDISABLED capability until TLS has been initialised
by the client issuing a STARTTLS. In all modes mode
plain-text authentication is ignored.
Also sets tls_listen.
.sp
.B tls_outgoing_force:
Do not send authentication information if TLS cannot be negotiated.
Also sets tls_outgoing.
.sp
.B
tls_all_force:
Short-Hand for tls_listen_force,tls_outgoing_force.
.TP
.B \-\-ssl_ca_chain_file:
Sets the optional all-in-one file where you can assemble the
certificates of Certification Authorities (CA) which form the
certificate chain of the server certificate. This starts with the
issuing CA certificate of the "ssl_cert_file" certificate and can
range up to the root CA certificate. Such a file is simply the
concatenation of the various PEM-encoded CA Certificate files, usually
in certificate chain order. Overrides ssl_ca_file and ssl_ca_path.
.br
(default NULL, no CA certificate will be used)
.TP
.B \-\-ssl_ca_file FILENAME:
Certificate Authorities to use when verifying certificates of real servers.
Used for SSL or TLS outgoing connections.  When building the Certificate
Authorities chain, ssl_ca_file is used first, if set, and then ssl_ca_path,
if set.  See SSL_CTX_load_verify_locations(3) for format details.
.br
(default "/etc/perdition/perdition.ca.pem")
.TP
.B \-\-ssl_ca_path PATHNAME:
Certificate Authorities to use when verifying certificates of real servers.
Used for SSL or TLS outgoing connections.  "openssh c_rehash" should be run
in this directory when new certificates are added.  When building the
Certificate Authorities chain, ssl_ca_file is used first, if set, and then
ssl_ca_path, if set.  See SSL_CTX_load_verify_locations(3) for details.
.br
(default "/etc/perdition/perdition.ca/")
.TP
.B \-\-ssl_ca_accept_self_signed:
Accept self-signed certificate authorities.
.TP
.B \-\-ssl_cert_file FILENAME:
Certificate to use when listening for SSL or TLS connections. 
Should be in PEM format.
.br
(default "/etc/perdition/perdition.crt.pem")
.TP 
.B \-\-ssl_cert_accept_self_signed:
Accept self-signed certificates.
Used for SSL or TLS outgoing connections.
.TP
.B \-\-ssl_cert_accept_expired:
Accept expired certificates. This includes server certificates
and certificate authority certificates.
Used for SSL or TLS outgoing connections.
.TP
.B \-\-ssl_cert_accept_not_yet_valid:
Accept certificates that are not yet valid. This includes server
certificates and certificate authority certificates.
Used for SSL or TLS outgoing connections.
.TP
.B \-\-ssl_cert_verify_depth DEPTH:
Chain Depth to recurse to when verifying certificates.
Used for SSL or TLS outgoing connections.
.br
(default 9)
.TP
.B \-\-ssl_key_file FILENAME:
Public key to use when listening for SSL or TLS connections. 
Should be in PEM format.
.br
(default "/etc/perdition/perdition.key.pem")
.TP
.B \-\-ssl_listen_ciphers STRING:
Cipher list when listening for SSL or TLS connections as per
ciphers(1). If empty ("") then openssl's default will be used.
.br
(default "")
.TP
.B \-\-ssl_outgoing_ciphers STRING:
Cipher list when making outgoing SSL or TLS connections as per 
ciphers(1). If empty ("") then openssl's default will be used.
.br
(default "")
.TP
.B \-\-ssl_no_cert_verify:
Don't cryptographically verify the real-server's certificate.
Used for SSL or TLS outgoing connections.
.TP
.B \-\-ssl_no_cn_verify:
Don't verify the real-server's common name with the name used.
to connect to the server. Used for SSL or TLS outgoing connections.
.TP
Notes: 
Default value for binary flags is off.
.br
If a string argument is empty ("") then the option will not
be used unless noted otherwise.
.br
The defaults given refer to the values if perdition is compiled with
--sysconfdir=/etc as it would for many binary distributions. For the
actual defaults of a given perdition binary run "perdition --help"
.SH USER DATABASE (POPMAP)
For information on mechanisms for resolving users to a host and port and
information on the \-M|\-\-map_library and \-m|\-\-map_library_opt flags, please
see \fBperditiondb\fP(5).
.PP
Note that by specifying an map library no map lookups will occur and
all connections will use the \-s|\-\-outgoing_server. In this way perdition
can be configured as a "pure proxy".
.SH STAND\-ALONE MODE
Normally perdition will bind to a port, and listen for connections.  The
default port is 110 in POP3 mode and 143 in IMAP4 mode, an alternate port
can be specified with the \-l|\-\-listen_port command line option. In this 
mode perdition will fork to manage clients.
.PP
.B Stand\-Alone Mode: Debian and RPM Installation
.PP
In the Debian and RPM distributions perdition can be started and 
stopped in stand\-alone mode using:
.PP
/etc/init.d/perdition start
.br
/etc/init.d/perdition stop
.PP
Editing /etc/sysconfig/perdition (RPM) or /etc/default/perdition
(Debian) allows control of whether perdition
will be started in POP3 mode, IMAP4 mode or both (or neither).
.PP
The syntax for this file is:
.PP
.nf
RUN_PERDITION=[yes|no]
FLAGS="flags"
POP3=[yes|no]
POP3_FLAGS="flags"
POP3S=[yes|no]
POP3S_FLAGS="flags"
IMAP4=[yes|no]
IMAP4_FLAGS="flags"
IMAP4S=[yes|no]
IMAP4S_FLAGS="flags"
.fi
.PP
The file is sourced into the init script so normal bash syntax
applies. Blank lines are ignored, as is anything after a # on a line.
.PP
e.g.
.PP
.nf
RUN_PERDITION=yes
POP3=on
POP3_FLAGS="--ssl_mode tls_listen"
POP3S=on
IMAP4_FLAGS="--ssl_mode tls_listen"
IMAP4=on
POP3S_FLAGS="--ssl_mode ssl_listen -p 110"
IMAP4S=on
IMAP4S_FLAGS="--ssl_mode ssl_listen -p 143"
.fi
.SH INETD MODE
Perdition can be used in conjunction with inetd. This enables perdition to
benefit from tcpd where access can be controlled to some extent using
/etc/hosts.allow and /etc/hosts.deny.
Sample /etc/inetd.conf entries follow:
.PP
pop3  stream tcp nowait root /usr/sbin/tcpd /usr/sbin/perdition.pop3 \-i
.br
pop3s stream tcp nowait root /usr/sbin/tcpd /usr/sbin/perdition.pop3s \-i
.br
imap2 stream tcp nowait root /usr/sbin/tcpd /usr/sbin/perdition.imap4 \-i
.br
imaps stream tcp nowait root /usr/sbin/tcpd /usr/sbin/perdition.imap4s \-i
.PP
inetd should then be restarted
.SH LOCAL AUTHENTICATION
If perdition has been compiled against libpam, it may  be set up to
authenticate the user locally once the USER and PASS commands are entered
by specifying the \-a|\-\-authenticate_in option on the command line. This
authentication happens before the connection to the foreign server is made
and must succeed for a connection to the foreign server to be made. 
.PP
This authentication uses PAM and a sample pam configuration file for
perdition can be found in etc/pam.d/perdition in the source tree. This
should be dropped into /etc/pam.d.
.SH DOMAIN DELIMITER
A multi character domain delimiter can be set using the \-d|\-\-domain
delimiter option. This sets the delimiter used in conjunction with the
\-S|\-\-strip_domain and \-c|\-\-client_server_specification options.
.SH USER PORT SPECIFICATION
If perdition is invoked with the \-c|\-\-client_server_specification flag
then the user may optionally specify the server and port that perdition
should connect to for the client using the syntax
user<delimiter>host[:port].
.PP
Example:
.nf
IMAP4

0 login henry@that.host:143

POP3

user james@other.host
.fi
.SH IDLE TIMEOUTS
If there is no input from the client or back\-end server for greater than
timeout seconds then the connection is closed. The default timeout is 1800
seconds and can be specified on the command line with the \-t|\-\-timeout
option.  A time out of 0 means that timeouts are disabled and clients and
back\-end servers can idle indefinitely.
.SH LOOP DETECTION
The greeting that perdition displays when accepting an incoming connection
is "+OK POP3 Ready <hostname>" or "* OK IMAP4 Ready <hostname>" in POP3 and
IMAP4 modes respectively. If when perdition connects to the back\-end server
the greeting string matches the greeting string of the perdition process
making the connection then it is assumed that perdition is connecting to
itself and a "Re\-Authentication Failure" is returned to the client.
.SH CONFIGURATION FILE
The format of a line of the configuration file is:
.PP
<key> <value>
.PP
Key is either a short or long option as per
perdition \-h|\-\-help, without the leading \- or \-\-.  Blank lines are
ignored, as is anything including and after a # (hash) on a
line. If a \\ precedes a new line then the lines will be concatenated.
IF a \\ precedes any other character, including a # (hash) it
will be treated as a literal. Anything inside single quotes (')
will be treated as a literal. Anything other than a (') inside
double quotes (") will be treated as a literal. Whitespace
in keys must be escaped or quoted. Whitespace in values
need not be escaped or quoted.
.P
Options that do not make sense in the configuration file such
as h|help and f|config_file  are ignored. Options specified on
the command line override the options in this file.
.PP
Example configuration File.
.nf
# perdition.conf
l           110             #Short option used as key
group       mail            #Long option used as key
a                           #Option with no argument
.fi
.SH POP BEFORE SMTP
Perdition supports POP before SMTP in both POP3 and IMAP4 mode
by logging having logging the following messages:
.P
When a user connects:
.P
Connect: <source_ip_address>[inetd_pid=<pid>]
.P
When a user is authenticated
.P
Auth: <source_ip_address> user="<username>" passwprd="<passwowd>" 
server="<servername"> port="<port>" status=failed...|ok
.P
When a user disconnects
.P
Close: <source_ip_address> user="<username>" received=<bytes> sent=<bytes>
.SH LOGGING
By default, logs are logged via syslog using the facility mail.  You should
inspect /etc/syslog.conf to find where these logs are written.  Under
Debian these logs will be written to /var/log/mail.log, under Red Hat 7.x 
these logs will be written to /var/log/maillog, under Solaris 8
these logs will be written to /var/log/syslog.  Normally each session will
have two perdition log entries.  Logs are prepended, depending on syslog
with the date, host, and perdition[<pid>]: .
.PP
Fatal errors are also logged with a priority of err. In stand\-alone mode
the startup parameters are logged on initialisation.  If the \-d|\-\-debug
command line option or configuration file directive is used then startup
parameters are logged regardless of other configuration directives and in
both stand\-alone and identd mode additional debugging messages are logged
with a priority of debug. As the flag implies, this is useful for debugging
but is probably too verbose for production systems. If the \-q|\-\-quiet
command line option or configuration file directive is used, only errors
will be logged. This is overridden by \-d|\-\-debug.
.SH SSL/TLS Support
Perdition supports using SSLv2 and SSLv3 to encrypt sessions between
end users and perdition and sessions between perdition and real servers.
SSL may be used for either, both or none of these classes of connections.
.P
The public key and certificate files should be in PEM format.
As a quick guide, the files may be generated using openssl with the
following command:
.nf
.P
openssl req \-new \-x509 \-nodes \\
  \-out perdition.crt.pem \-keyout perdition.key.pem \-days 365
.fi
.SH FILES
.TP
\fC/etc/perdition/perdition.conf
.SH SEE ALSO
perditiondb(5), inetd(8), syslog.conf(5), syslogd(8)
.SH AUTHORS
.B Lead
.br
Horms <horms@verge.net.au>
.PP
.B Perditiondb Library Authors
.br
Frederic Delchambre <dedel@freegates.be>      (MySQL)
.br
Chris Stratford: <chriss@uk.uu.net>           (LDAP and Berkeley DB)
.br
Nathan Neulinger <nneul@umr.edu>              (NIS)
.PP
.B Contributing Authors
.br
Daniel Roesen <droesen@entire\-systems.com>
.br
Clinton Work <work@scripty.com>
.br
Youri <ya@linkline.be>
.br
Jeremy Nelson <jnelson@optusnet.com.au>
.br
Wim Bonis <bonis@solution\-service.de>
.br
Arvid Requate <arvid@Team.OWL\-Online.DE>
.br
Mikolaj J. Habryn <dichro@rcpt.to>
.br
Ronny Cook <ronny@asiaonline.net>
.br
Geoff Mitchell <g.mitchell@videonetworks.com>
.br
Willi Langenberger <wlang@wu\-wien.ac.at>
.br
Matt Prigge <mprigge@pobox.com>
.br
Wolfgang Breyha <wolfgang.breyha@uta.at>
