.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" perditiondb_postgresql_makedb.8                        December 2000
.\" Horms                                             horms@verge.net.au
.\"
.\" perdition
.\" Mail retrieval proxy server
.\" Copyright (C) 1999-2005  Horms <horms@verge.net.au>
.\" 
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of the
.\" License, or (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307  USA
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH PERDITIONDB_POSTGRESQL_MAKEDB 8 "26th December 2000"
.SH NAME
perditiondb_postgresql_makedb \- create perdition database in a PostgreSQL
RDMS
.SH SYNOPSIS
\fBperditiondb_postgresql_makedb\fP
.SH DESCRIPTION
\fBperditiondb_postgresql_makedb\fP is an interactive programme
to help seed a database in a PostgreSQL RDMS to store associations
between users and servers for perdition.
.SH OPTIONS
.TP
None \- All input is promted for by the programme.
.SH FILES
.TP
None
.SH SEE ALSO
perditiondb(5), perdition(8)
.SH AUTHORS
.br
Horms <horms@verge.net.au>
