#!/bin/sh
######################################################################
# perditiondb_postgresql_makedb                             April 2000
# Horms                                             horms@vergenet.net
#
# Sample programme to create a PostgreSQL database 
#
# Adapted from a similar script for MySQL by 
# Frederic Delchambre <dedel@freegates.be>
#
# perdition
# Mail retreival proxy server
# Copyright (C) 1999  Horms
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307  USA
#
######################################################################



#Create user perdition in the database
echo "Enter Password for user postgres"
su postgres -c "\
  echo y | destroyuser -q perdition ; \
  createuser -d -i $(id -u)  -U perdition ; \
  psql -q template1 -c \" \
  	update pg_shadow set passwd='flim',\
	valuntil='Fri Jan 30 22:00:00 2037 PST' \
	where usename='perdition';\" " > /dev/null


#Create database as user perdition
createdb -u dbPerdition > /dev/null << _EOF_
perdition
perdition
_EOF_

#Seed table with data as user perdition
psql -q -u  dbPerdition << _EOF_
perdition
perdition
create table tblPerdition (
  "user" char(16) not null primary key, 
  "servername" char(255) not null, 
  "port" char(8) default null
);
insert into tblPerdition values ('dedel', 'mail.freegates.be', '');
insert into tblPerdition values ('fred', 'mail.nts.be', '1974');
insert into tblPerdition values ('tymm', 'localhost',   '');
insert into tblPerdition values ('horms','localhost',   '');
_EOF_
