#!/bin/bash
######################################################################
# perditiondb_ldap_makedb                                     May 2000
# Horms                                             horms@vergenet.net
#
# Sample programme to make an LDAP based popmap
#
# perdition
# Mail retreival proxy server
# Copyright (C) 1999  Horms
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307  USA
#
######################################################################


#Edit this to reflect your ldap setup
DC="cn=Manager, dc=my-domain, dc=com"


##########################################
# No user servicable parts below this line

cat << __EOF__
Initialising LDAP popmap...

You will need to enter the sevret for the
binddn: "$DC".
The default mau be "secret", you should change
your ldap configuration if this is the case.

__EOF__

ldapadd -D "$DC" -W << __EOF__
dn: dc=my-domain, dc=com
dc: my-domain

dn: ou=mailbox, dc=my-domain, dc=com
ou: mailbox

dn: uid=horms, ou=mailbox,  dc=my-domain, dc=com
uid: horms
username: horms
mailhost: localhost
port: 110

dn: uid=tymm, ou=mailbox, dc=my-domain, dc=com
uid: tymm
username: tymm
mailhost: localhost
__EOF__
